// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsVrPYUAs9gZhm6DjN5HoOpkSoMrMt1w0',
    appId: '1:417605336184:web:384a3cfcc4bbb51d96818d',
    messagingSenderId: '417605336184',
    projectId: 'capstone-48868',
    authDomain: 'capstone-48868.firebaseapp.com',
    storageBucket: 'capstone-48868.firebasestorage.app',
    measurementId: 'G-VHXY4GN0N8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc2uN3BRhW_u-C7SAtoXSscQic2eCI9SA',
    appId: '1:417605336184:android:498e7d0d6c17c2f296818d',
    messagingSenderId: '417605336184',
    projectId: 'capstone-48868',
    storageBucket: 'capstone-48868.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC11LAkLQCAY8Dr0GW__7byALmWYQGHXjE',
    appId: '1:417605336184:ios:b861f18d59f5abb396818d',
    messagingSenderId: '417605336184',
    projectId: 'capstone-48868',
    storageBucket: 'capstone-48868.firebasestorage.app',
    iosBundleId: 'com.example.capstonea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC11LAkLQCAY8Dr0GW__7byALmWYQGHXjE',
    appId: '1:417605336184:ios:b861f18d59f5abb396818d',
    messagingSenderId: '417605336184',
    projectId: 'capstone-48868',
    storageBucket: 'capstone-48868.firebasestorage.app',
    iosBundleId: 'com.example.capstonea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsVrPYUAs9gZhm6DjN5HoOpkSoMrMt1w0',
    appId: '1:417605336184:web:315235842bc8ebb896818d',
    messagingSenderId: '417605336184',
    projectId: 'capstone-48868',
    authDomain: 'capstone-48868.firebaseapp.com',
    storageBucket: 'capstone-48868.firebasestorage.app',
    measurementId: 'G-BN5G6064CH',
  );

}