name: capstone_a
description: "A new Flutter project."

publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.6

  cupertino_icons: ^1.0.8
  # ADD THESE for Firebase:
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/images/
    - assets/images/AppIcon.png
    - assets/images/lung.png
    - assets/images/heart.png
